# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 710)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1120, 710))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1131, 711))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(250, 390, 621, 52))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setTextFormat(QtCore.Qt.PlainText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_7.addWidget(self.label_11)
        self.lineEdit_topic = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEdit_topic.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit_topic.setFont(font)
        self.lineEdit_topic.setObjectName("lineEdit_topic")
        self.horizontalLayout_7.addWidget(self.lineEdit_topic)
        self.pushButton_submit = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_submit.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_submit.setFont(font)
        self.pushButton_submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_submit.setObjectName("pushButton_submit")
        self.horizontalLayout_7.addWidget(self.pushButton_submit)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(250, 110, 621, 80))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_8.addWidget(self.label_12)
        self.lineEdit_host = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_host.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit_host.setFont(font)
        self.lineEdit_host.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_host.setObjectName("lineEdit_host")
        self.horizontalLayout_8.addWidget(self.lineEdit_host)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.lineEdit_port = QtWidgets.QLineEdit(self.horizontalLayoutWidget_5)
        self.lineEdit_port.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit_port.setFont(font)
        self.lineEdit_port.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.horizontalLayout_8.addWidget(self.lineEdit_port)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(250, 200, 621, 80))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_9.addWidget(self.label_14)
        self.lineEdit_username = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineEdit_username.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit_username.setFont(font)
        self.lineEdit_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.horizontalLayout_9.addWidget(self.lineEdit_username)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem1)
        self.label_15 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.lineEdit_password = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineEdit_password.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit_password.setFont(font)
        self.lineEdit_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_9.addWidget(self.lineEdit_password)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(250, 290, 621, 80))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.lineEdit_clientid = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_clientid.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit_clientid.setFont(font)
        self.lineEdit_clientid.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_clientid.setObjectName("lineEdit_clientid")
        self.horizontalLayout_10.addWidget(self.lineEdit_clientid)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem2)
        self.label_17 = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.lineEdit_heartbeat = QtWidgets.QLineEdit(self.horizontalLayoutWidget_7)
        self.lineEdit_heartbeat.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit_heartbeat.setFont(font)
        self.lineEdit_heartbeat.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_heartbeat.setObjectName("lineEdit_heartbeat")
        self.horizontalLayout_10.addWidget(self.lineEdit_heartbeat)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 5, 601, 52))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setTextFormat(QtCore.Qt.PlainText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.lineEdit_topic_rec = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_topic_rec.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.lineEdit_topic_rec.setFont(font)
        self.lineEdit_topic_rec.setText("")
        self.lineEdit_topic_rec.setObjectName("lineEdit_topic_rec")
        self.horizontalLayout_4.addWidget(self.lineEdit_topic_rec)
        self.label_img = QtWidgets.QLabel(self.tab)
        self.label_img.setGeometry(QtCore.QRect(10, 50, 600, 600))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_img.setFont(font)
        self.label_img.setAutoFillBackground(False)
        self.label_img.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_img.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_img.setLineWidth(3)
        self.label_img.setMidLineWidth(0)
        self.label_img.setTextFormat(QtCore.Qt.PlainText)
        self.label_img.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img.setObjectName("label_img")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(630, 50, 370, 381))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(27, 27, 83);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_status = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_status.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_status.setFont(font)
        self.label_status.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_status.setTextFormat(QtCore.Qt.PlainText)
        self.label_status.setScaledContents(False)
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.verticalLayout_2.addWidget(self.label_status)
        self.label_mode = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_mode.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_mode.setFont(font)
        self.label_mode.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_mode.setTextFormat(QtCore.Qt.PlainText)
        self.label_mode.setScaledContents(False)
        self.label_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mode.setObjectName("label_mode")
        self.verticalLayout_2.addWidget(self.label_mode)
        self.label_time = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_time.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_time.setFont(font)
        self.label_time.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_time.setTextFormat(QtCore.Qt.PlainText)
        self.label_time.setScaledContents(False)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.verticalLayout_2.addWidget(self.label_time)
        self.label_lat = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_lat.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_lat.setFont(font)
        self.label_lat.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_lat.setTextFormat(QtCore.Qt.PlainText)
        self.label_lat.setScaledContents(False)
        self.label_lat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lat.setObjectName("label_lat")
        self.verticalLayout_2.addWidget(self.label_lat)
        self.label_lon = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_lon.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_lon.setFont(font)
        self.label_lon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_lon.setTextFormat(QtCore.Qt.PlainText)
        self.label_lon.setScaledContents(False)
        self.label_lon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lon.setObjectName("label_lon")
        self.verticalLayout_2.addWidget(self.label_lon)
        self.label_speed = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_speed.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_speed.setFont(font)
        self.label_speed.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_speed.setTextFormat(QtCore.Qt.PlainText)
        self.label_speed.setScaledContents(False)
        self.label_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_speed.setObjectName("label_speed")
        self.verticalLayout_2.addWidget(self.label_speed)
        self.label_course = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_course.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_course.setFont(font)
        self.label_course.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_course.setTextFormat(QtCore.Qt.PlainText)
        self.label_course.setScaledContents(False)
        self.label_course.setAlignment(QtCore.Qt.AlignCenter)
        self.label_course.setObjectName("label_course")
        self.verticalLayout_2.addWidget(self.label_course)
        self.label_declination = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_declination.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_declination.setFont(font)
        self.label_declination.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_declination.setTextFormat(QtCore.Qt.PlainText)
        self.label_declination.setScaledContents(False)
        self.label_declination.setAlignment(QtCore.Qt.AlignCenter)
        self.label_declination.setObjectName("label_declination")
        self.verticalLayout_2.addWidget(self.label_declination)
        self.label_declination_dir = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_declination_dir.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_declination_dir.setFont(font)
        self.label_declination_dir.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_declination_dir.setTextFormat(QtCore.Qt.PlainText)
        self.label_declination_dir.setScaledContents(False)
        self.label_declination_dir.setAlignment(QtCore.Qt.AlignCenter)
        self.label_declination_dir.setObjectName("label_declination_dir")
        self.verticalLayout_2.addWidget(self.label_declination_dir)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3.setStretch(1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.tab)
        self.pushButton_reset.setGeometry(QtCore.QRect(1010, 250, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton_start = QtWidgets.QPushButton(self.tab)
        self.pushButton_start.setGeometry(QtCore.QRect(1010, 90, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_stop = QtWidgets.QPushButton(self.tab)
        self.pushButton_stop.setGeometry(QtCore.QRect(1010, 170, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(630, 440, 471, 211))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_debug = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_debug.setAutoFillBackground(False)
        self.label_debug.setStyleSheet("color: rgb(170, 85, 0);")
        self.label_debug.setFrameShape(QtWidgets.QFrame.Box)
        self.label_debug.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_debug.setTextFormat(QtCore.Qt.PlainText)
        self.label_debug.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_debug.setWordWrap(False)
        self.label_debug.setObjectName("label_debug")
        self.horizontalLayout_5.addWidget(self.label_debug)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton_clear = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_clear.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_clear.setFont(font)
        self.pushButton_clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.horizontalLayout_5.addWidget(self.pushButton_clear)
        self.horizontalLayout_5.setStretch(0, 2)
        self.label_gpsupdate = QtWidgets.QLabel(self.tab)
        self.label_gpsupdate.setGeometry(QtCore.QRect(1013, 340, 81, 41))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(12)
        self.label_gpsupdate.setFont(font)
        self.label_gpsupdate.setStyleSheet("")
        self.label_gpsupdate.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_gpsupdate.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_gpsupdate.setTextFormat(QtCore.Qt.PlainText)
        self.label_gpsupdate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_gpsupdate.setObjectName("label_gpsupdate")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setGeometry(QtCore.QRect(90, 60, 380, 261))
        self.widget.setStyleSheet("background-color: rgb(245, 255, 180);")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 40, 361, 221))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_18.setTextFormat(QtCore.Qt.PlainText)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.label_19 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_19.setTextFormat(QtCore.Qt.PlainText)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_3.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_20.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_20.setTextFormat(QtCore.Qt.PlainText)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_3.addWidget(self.label_20)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem4)
        self.label_yaw = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_yaw.setFont(font)
        self.label_yaw.setStyleSheet("color: rgb(109, 0, 82);")
        self.label_yaw.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_yaw.setTextFormat(QtCore.Qt.PlainText)
        self.label_yaw.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yaw.setObjectName("label_yaw")
        self.verticalLayout_4.addWidget(self.label_yaw)
        self.label_yaw_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_yaw_3.setFont(font)
        self.label_yaw_3.setStyleSheet("color: rgb(109, 0, 82);")
        self.label_yaw_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_yaw_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_yaw_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yaw_3.setObjectName("label_yaw_3")
        self.verticalLayout_4.addWidget(self.label_yaw_3)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.label_roll = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_roll.setFont(font)
        self.label_roll.setStyleSheet("color: rgb(109, 0, 82);")
        self.label_roll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_roll.setTextFormat(QtCore.Qt.PlainText)
        self.label_roll.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roll.setObjectName("label_roll")
        self.verticalLayout_4.addWidget(self.label_roll)
        self.label_roll_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_roll_3.setFont(font)
        self.label_roll_3.setStyleSheet("color: rgb(109, 0, 82);")
        self.label_roll_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_roll_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_roll_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roll_3.setObjectName("label_roll_3")
        self.verticalLayout_4.addWidget(self.label_roll_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.label_pitch = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_pitch.setFont(font)
        self.label_pitch.setStyleSheet("color: rgb(109, 0, 82);")
        self.label_pitch.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_pitch.setTextFormat(QtCore.Qt.PlainText)
        self.label_pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitch.setObjectName("label_pitch")
        self.verticalLayout_4.addWidget(self.label_pitch)
        self.label_pitch_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(11)
        self.label_pitch_3.setFont(font)
        self.label_pitch_3.setStyleSheet("color: rgb(109, 0, 82);")
        self.label_pitch_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_pitch_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_pitch_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitch_3.setObjectName("label_pitch_3")
        self.verticalLayout_4.addWidget(self.label_pitch_3)
        spacerItem7 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        spacerItem8 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem8)
        self.label_yaw_v = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_yaw_v.setFont(font)
        self.label_yaw_v.setFrameShape(QtWidgets.QFrame.Box)
        self.label_yaw_v.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_yaw_v.setText("")
        self.label_yaw_v.setTextFormat(QtCore.Qt.PlainText)
        self.label_yaw_v.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yaw_v.setObjectName("label_yaw_v")
        self.verticalLayout_11.addWidget(self.label_yaw_v)
        self.label_yaw_dot = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_yaw_dot.setFont(font)
        self.label_yaw_dot.setFrameShape(QtWidgets.QFrame.Box)
        self.label_yaw_dot.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_yaw_dot.setText("")
        self.label_yaw_dot.setTextFormat(QtCore.Qt.PlainText)
        self.label_yaw_dot.setAlignment(QtCore.Qt.AlignCenter)
        self.label_yaw_dot.setObjectName("label_yaw_dot")
        self.verticalLayout_11.addWidget(self.label_yaw_dot)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.label_roll_v = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_roll_v.setFont(font)
        self.label_roll_v.setFrameShape(QtWidgets.QFrame.Box)
        self.label_roll_v.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_roll_v.setText("")
        self.label_roll_v.setTextFormat(QtCore.Qt.PlainText)
        self.label_roll_v.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roll_v.setObjectName("label_roll_v")
        self.verticalLayout_11.addWidget(self.label_roll_v)
        self.label_roll_dot = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_roll_dot.setFont(font)
        self.label_roll_dot.setFrameShape(QtWidgets.QFrame.Box)
        self.label_roll_dot.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_roll_dot.setText("")
        self.label_roll_dot.setTextFormat(QtCore.Qt.PlainText)
        self.label_roll_dot.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roll_dot.setObjectName("label_roll_dot")
        self.verticalLayout_11.addWidget(self.label_roll_dot)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem10)
        self.label_pitch_v = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_pitch_v.setFont(font)
        self.label_pitch_v.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pitch_v.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_pitch_v.setText("")
        self.label_pitch_v.setTextFormat(QtCore.Qt.PlainText)
        self.label_pitch_v.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitch_v.setObjectName("label_pitch_v")
        self.verticalLayout_11.addWidget(self.label_pitch_v)
        self.label_pitch_dot = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        self.label_pitch_dot.setFont(font)
        self.label_pitch_dot.setFrameShape(QtWidgets.QFrame.Box)
        self.label_pitch_dot.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_pitch_dot.setText("")
        self.label_pitch_dot.setTextFormat(QtCore.Qt.PlainText)
        self.label_pitch_dot.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pitch_dot.setObjectName("label_pitch_dot")
        self.verticalLayout_11.addWidget(self.label_pitch_dot)
        spacerItem11 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem11)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.horizontalLayout.setStretch(2, 1)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 361, 20))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setTextFormat(QtCore.Qt.PlainText)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.widget_2 = QtWidgets.QWidget(self.tab_4)
        self.widget_2.setGeometry(QtCore.QRect(640, 60, 380, 261))
        self.widget_2.setStyleSheet("background-color: rgb(245, 255, 180);")
        self.widget_2.setObjectName("widget_2")
        self.label_26 = QtWidgets.QLabel(self.widget_2)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 361, 20))
        font = QtGui.QFont()
        font.setFamily("隶书")
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setTextFormat(QtCore.Qt.PlainText)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.widget_2)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(10, 40, 361, 221))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_27 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_27.setTextFormat(QtCore.Qt.PlainText)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_7.addWidget(self.label_27)
        self.label_28 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_28.setTextFormat(QtCore.Qt.PlainText)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_7.addWidget(self.label_28)
        self.label_29 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_29.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_29.setTextFormat(QtCore.Qt.PlainText)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_7.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_30.setTextFormat(QtCore.Qt.PlainText)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_7.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(27, 27, 83);")
        self.label_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_31.setTextFormat(QtCore.Qt.PlainText)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_7.addWidget(self.label_31)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem12 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem12)
        self.label_motor1 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_motor1.setFrameShape(QtWidgets.QFrame.Box)
        self.label_motor1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_motor1.setText("")
        self.label_motor1.setTextFormat(QtCore.Qt.PlainText)
        self.label_motor1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor1.setObjectName("label_motor1")
        self.verticalLayout_8.addWidget(self.label_motor1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem13)
        self.label_motor2 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_motor2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_motor2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_motor2.setText("")
        self.label_motor2.setTextFormat(QtCore.Qt.PlainText)
        self.label_motor2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor2.setObjectName("label_motor2")
        self.verticalLayout_8.addWidget(self.label_motor2)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem14)
        self.label_motor3 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_motor3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_motor3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_motor3.setText("")
        self.label_motor3.setTextFormat(QtCore.Qt.PlainText)
        self.label_motor3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor3.setObjectName("label_motor3")
        self.verticalLayout_8.addWidget(self.label_motor3)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem15)
        self.label_motor4 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_motor4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_motor4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_motor4.setText("")
        self.label_motor4.setTextFormat(QtCore.Qt.PlainText)
        self.label_motor4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor4.setObjectName("label_motor4")
        self.verticalLayout_8.addWidget(self.label_motor4)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem16)
        self.label_motor5 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_motor5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_motor5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_motor5.setText("")
        self.label_motor5.setTextFormat(QtCore.Qt.PlainText)
        self.label_motor5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_motor5.setObjectName("label_motor5")
        self.verticalLayout_8.addWidget(self.label_motor5)
        spacerItem17 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem17)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.horizontalLayout_6.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1120, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton_start.clicked.connect(self.Start)
        self.pushButton_stop.clicked.connect(self.Stop)
        self.pushButton_reset.clicked.connect(self.Reset)
        self.pushButton_clear.clicked.connect(self.Clear)
        self.pushButton_submit.clicked.connect(self.Subs)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GPS Map"))
        self.label_11.setText(_translate("MainWindow", "Topic"))
        self.lineEdit_topic.setText(_translate("MainWindow", "/CC3200@SHIP/2/SHIPDATA/SENSORDATA"))
        self.lineEdit_topic.setPlaceholderText(_translate("MainWindow", "订阅主题"))
        self.pushButton_submit.setText(_translate("MainWindow", "Submit"))
        self.label_12.setText(_translate("MainWindow", "Host"))
        self.lineEdit_host.setText(_translate("MainWindow", "139.199.208.33"))
        self.lineEdit_host.setPlaceholderText(_translate("MainWindow", "服务器IP"))
        self.label_13.setText(_translate("MainWindow", "Port"))
        self.lineEdit_port.setText(_translate("MainWindow", "1883"))
        self.lineEdit_port.setPlaceholderText(_translate("MainWindow", "端口"))
        self.label_14.setText(_translate("MainWindow", "Username"))
        self.lineEdit_username.setText(_translate("MainWindow", "cehang"))
        self.lineEdit_username.setPlaceholderText(_translate("MainWindow", "用户名"))
        self.label_15.setText(_translate("MainWindow", "Password"))
        self.lineEdit_password.setText(_translate("MainWindow", "cehang001"))
        self.lineEdit_password.setPlaceholderText(_translate("MainWindow", "密码"))
        self.label_16.setText(_translate("MainWindow", "CliendID"))
        self.lineEdit_clientid.setText(_translate("MainWindow", "SXF_Python_Map"))
        self.lineEdit_clientid.setPlaceholderText(_translate("MainWindow", "连接ID"))
        self.label_17.setText(_translate("MainWindow", "HeartBeat"))
        self.lineEdit_heartbeat.setText(_translate("MainWindow", "60"))
        self.lineEdit_heartbeat.setPlaceholderText(_translate("MainWindow", "心跳"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "  连接  "))
        self.label_10.setText(_translate("MainWindow", "Receive Topic"))
        self.label_img.setText(_translate("MainWindow", "GPS Map Here"))
        self.label.setText(_translate("MainWindow", "状态"))
        self.label_2.setText(_translate("MainWindow", "模式"))
        self.label_3.setText(_translate("MainWindow", "时间"))
        self.label_4.setText(_translate("MainWindow", "纬度"))
        self.label_5.setText(_translate("MainWindow", "经度"))
        self.label_6.setText(_translate("MainWindow", "速率"))
        self.label_7.setText(_translate("MainWindow", "航向"))
        self.label_8.setText(_translate("MainWindow", "磁偏"))
        self.label_9.setText(_translate("MainWindow", "偏向"))
        self.label_status.setText(_translate("MainWindow", "A有效;V无效"))
        self.label_mode.setText(_translate("MainWindow", "A自主;D差分;E估算; N无效"))
        self.label_time.setText(_translate("MainWindow", "年/月/日 时:分:秒"))
        self.label_lat.setText(_translate("MainWindow", "N北纬;S南纬"))
        self.label_lon.setText(_translate("MainWindow", "E东经;W西经"))
        self.label_speed.setText(_translate("MainWindow", "公里/小时"))
        self.label_course.setText(_translate("MainWindow", "0~359.9°"))
        self.label_declination.setText(_translate("MainWindow", "0~180.0°"))
        self.label_declination_dir.setText(_translate("MainWindow", "E东;W西"))
        self.pushButton_reset.setText(_translate("MainWindow", "Reset"))
        self.pushButton_start.setText(_translate("MainWindow", "Start"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.label_debug.setText(_translate("MainWindow", "DeBug Here"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.label_gpsupdate.setText(_translate("MainWindow", "定位未更新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "  GPS  "))
        self.label_18.setText(_translate("MainWindow", "偏航角(yaw)"))
        self.label_19.setText(_translate("MainWindow", "滚转角(roll)"))
        self.label_20.setText(_translate("MainWindow", "俯仰角(pitch)"))
        self.label_yaw.setText(_translate("MainWindow", "角度"))
        self.label_yaw_3.setText(_translate("MainWindow", "角加速度"))
        self.label_roll.setText(_translate("MainWindow", "角度"))
        self.label_roll_3.setText(_translate("MainWindow", "角加速度"))
        self.label_pitch.setText(_translate("MainWindow", "角度"))
        self.label_pitch_3.setText(_translate("MainWindow", "角加速度"))
        self.label_21.setText(_translate("MainWindow", "MPU6050姿态传感器"))
        self.label_26.setText(_translate("MainWindow", "A365电机转速"))
        self.label_27.setText(_translate("MainWindow", "电机1"))
        self.label_28.setText(_translate("MainWindow", "电机2"))
        self.label_29.setText(_translate("MainWindow", "电机3"))
        self.label_30.setText(_translate("MainWindow", "电机4"))
        self.label_31.setText(_translate("MainWindow", "电机5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", " 传感器 "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "  控制  "))


